### ISSUE TITLE
#6 Fix remaining functional tests (M)

### ISSUE THREAD

**Issue by ayajaff** [Alster-Hamburgers/leap_web#6]
So we have fixed all the unit tests but there are still a few functional tests that are failing. We think it's an M because we definitely can't solve this on our own and need a coach for this one.

**Comment by ankonym** [comment]
Fixed by removing the test altogether - it failed because of the added invite code field in the signup form but it actually tested code that is currently unused (the change password form that is currently not shown to any users, and that already contains a workaround to hide the signup form's login field).

**Comment by ankonym** [comment]
Merged in pull request #194 to leapcode/leap_web
